spring:
  redis:
    clusterA:
      host: dcluster.morehouse.com
      port: 12000
      ssl: true
    clusterB:
      host: dcluster.morehouse.com
      port: 12000
      ssl: true

resilience4j:
  circuitbreaker:
    instances:
      redisServiceCB:      # The circuit breaker name we'll use
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 5           # Reduced window size
        failureRateThreshold: 50
        waitDurationInOpenState: 3s    # Check more frequently
        permittedNumberOfCallsInHalfOpenState: 2  # Fewer test calls needed
        automaticTransitionFromOpenToHalfOpenEnabled: true
        minimumNumberOfCalls: 2        # Fewer calls needed to calculate failure rate
        recordExceptions:
          - org.springframework.data.redis.RedisSystemException
          - io.lettuce.core.RedisException
        ignoreExceptions: []

management:
  endpoints:
    web:
      exposure:
        include: health,circuitbreakers
  health:
    circuitbreakers:
      enabled: true

